#!/bin/bash
set -e

# Strip leading 'v' if present (handle both '10.10.7' and 'v10.10.7')
RAW_VERSION=${JELLYFIN_WEB_VERSION:-"10.10.7"}
JELLYFIN_WEB_VERSION="${RAW_VERSION#v}"

JELLYFIN_WEB_RELEASE_URL="https://github.com/jellyfin/jellyfin-web/archive/refs/tags/v${JELLYFIN_WEB_VERSION}.tar.gz"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build"
DIST_DIR="${SCRIPT_DIR}/dist"
SRC_DIR="${SCRIPT_DIR}/src"

echo "============================================"
echo " Jellyfin Web Emby Adapter Build Script"
echo "============================================"
echo ""
echo "Jellyfin Web Version: ${JELLYFIN_WEB_VERSION}"
echo "Download URL: ${JELLYFIN_WEB_RELEASE_URL}"
echo "Build Directory: ${BUILD_DIR}"
echo "Distribution Directory: ${DIST_DIR}"
echo ""

# Clean previous build
echo "[1/7] Cleaning previous build..."
rm -rf "${BUILD_DIR}" "${DIST_DIR}"
mkdir -p "${BUILD_DIR}" "${DIST_DIR}"

# Download jellyfin-web source
echo "[2/7] Downloading jellyfin-web v${JELLYFIN_WEB_VERSION}..."
TARBALL="${BUILD_DIR}/jellyfin-web-${JELLYFIN_WEB_VERSION}.tar.gz"
curl -fSL "${JELLYFIN_WEB_RELEASE_URL}" -o "${TARBALL}"

# Extract source
echo "[3/7] Extracting source..."
tar xzf "${TARBALL}" -C "${BUILD_DIR}"
JELLYFIN_SRC="${BUILD_DIR}/jellyfin-web-${JELLYFIN_WEB_VERSION}"

if [ ! -d "${JELLYFIN_SRC}" ]; then
    echo "Error: Expected source directory not found: ${JELLYFIN_SRC}"
    exit 1
fi

# Install dependencies
echo "[4/7] Installing dependencies..."
cd "${JELLYFIN_SRC}"
npm ci --no-audit 2>&1 | tail -5

# ========================================
# PATCH: Disable version check in node_modules (belt-and-suspenders)
# ========================================
echo "[5/7] Patching version checks in node_modules..."

# --- jellyfin-apiclient ---
echo "  - Patching jellyfin-apiclient initial version value..."
find "${JELLYFIN_SRC}/node_modules" -name "*.js" -path "*jellyfin-apiclient*" \
  -exec grep -l "_minServerVersion" {} \; 2>/dev/null | while read f; do
    echo "    Patching: $f"
    sed -i "s/\._minServerVersion\s*=\s*['\"][0-9.]*['\"]/._minServerVersion = '0.0.0'/g" "$f"
done

# --- @jellyfin/sdk ---
echo "  - Patching @jellyfin/sdk MINIMUM_VERSION..."
if [ -d "${JELLYFIN_SRC}/node_modules/@jellyfin/sdk" ]; then
    find "${JELLYFIN_SRC}/node_modules/@jellyfin/sdk" \( -name "*.js" -o -name "*.ts" \) 2>/dev/null | while read f; do
        if grep -q "MINIMUM_VERSION" "$f" 2>/dev/null; then
            echo "    Patching: $f"
            sed -i "s/MINIMUM_VERSION\s*=\s*['\"][0-9.]*['\"]/MINIMUM_VERSION = '0.0.0'/g" "$f"
        fi
    done
fi

echo "  Version patches applied."

# ========================================
# PATCH: Inject Emby adapter import into entry point
# ========================================
echo "[6/7] Injecting Emby adapter..."

# Copy adapter source files into the jellyfin-web source tree
ADAPTER_DEST="${JELLYFIN_SRC}/src/emby-adapter"
mkdir -p "${ADAPTER_DEST}"
cp "${SRC_DIR}/emby-adapter/embyAdapter.js" "${ADAPTER_DEST}/"
cp "${SRC_DIR}/emby-adapter/index.js" "${ADAPTER_DEST}/"

# ========================================
# CRITICAL FIX: Ensure embyAdapter.js is treated as an ES module by Babel.
#
# embyAdapter.js is an IIFE with no import/export statements. Babel's
# sourceType:'unambiguous' would classify it as a 'script', but webpack
# treats it as an ES module (because it is imported via `import` statement).
# When @babel/preset-env injects core-js polyfills with useBuiltIns:'usage',
# the mismatch between Babel's script mode (require) and webpack's ESM
# expectation (import) causes the production build to fail.
#
# Appending `export {};` makes Babel recognize the file as an ES module,
# ensuring polyfill injections use consistent `import` syntax.
# ========================================
echo "  Ensuring embyAdapter.js has ES module export for Babel compatibility..."
if ! grep -q '^export' "${ADAPTER_DEST}/embyAdapter.js"; then
    printf '\n// Ensure Babel (sourceType: unambiguous) treats this file as an ES module\nexport {};\n' >> "${ADAPTER_DEST}/embyAdapter.js"
    echo "  Added 'export {};' to embyAdapter.js"
fi

# Find the main entry point and inject adapter import at the top
ENTRY_FILE="${JELLYFIN_SRC}/src/index.jsx"
if [ ! -f "${ENTRY_FILE}" ]; then
    ENTRY_FILE="${JELLYFIN_SRC}/src/index.js"
fi
if [ ! -f "${ENTRY_FILE}" ]; then
    ENTRY_FILE=$(find "${JELLYFIN_SRC}/src" -maxdepth 1 -name "index.*" | head -1)
fi

if [ -f "${ENTRY_FILE}" ]; then
    echo "  Injecting into entry point: ${ENTRY_FILE}"
    TMPFILE=$(mktemp)
    cat > "${TMPFILE}" << 'ADAPTER_INJECT'
// === Emby Adapter Injection (auto-generated by build.sh) ===
import './emby-adapter/embyAdapter.js';
import './emby-adapter/index.js';
// === End Emby Adapter Injection ===

ADAPTER_INJECT
    cat "${ENTRY_FILE}" >> "${TMPFILE}"
    mv "${TMPFILE}" "${ENTRY_FILE}"
    echo "  Adapter injected successfully."
else
    echo "  WARNING: Could not find entry point to inject adapter!"
    echo "  Will fall back to copying adapter files to dist."
fi

# Build
echo "[7/7] Building jellyfin-web (this may take a while)..."
npm run build:production 2>&1 | tail -20

DIST_SRC="${JELLYFIN_SRC}/dist"
if [ ! -d "${DIST_SRC}" ]; then
    echo "Error: Build output not found at ${DIST_SRC}"
    exit 1
fi

# Copy build output to dist
cp -r "${DIST_SRC}"/* "${DIST_DIR}/"

# Also copy adapter files to dist as fallback (in case webpack didn't bundle them)
echo "  Copying standalone adapter files to dist as fallback..."
cp "${SRC_DIR}/emby-adapter/embyAdapter.js" "${DIST_DIR}/embyAdapter.js"
cp "${SRC_DIR}/emby-adapter/index.js" "${DIST_DIR}/embySetup.js"

# ========================================
# CRITICAL: Copy Service Worker to dist root
# ========================================
# The Service Worker MUST be at the root of the served directory
# so its scope covers all pages. It cannot be bundled by webpack
# because it runs in a separate context (ServiceWorkerGlobalScope).
echo "  Copying Service Worker (sw.js) to dist root..."
cp "${SRC_DIR}/emby-adapter/sw.js" "${DIST_DIR}/sw.js"

# Inject script tags into index.html if adapter wasn't bundled
if [ -f "${DIST_DIR}/index.html" ]; then
    if ! grep -q "embyAdapter" "${DIST_DIR}/index.html"; then
        echo "  Injecting adapter script tags into index.html..."
        sed -i 's|</head>|<script src="embyAdapter.js"></script>\n<script src="embySetup.js"></script>\n</head>|' "${DIST_DIR}/index.html"
    fi
fi

cd "${SCRIPT_DIR}"

# Clean up build directory
rm -rf "${BUILD_DIR}"

echo ""
echo "============================================"
echo " Build Complete!"
echo "============================================"
echo "Output: ${DIST_DIR}"
echo ""
echo "Files in dist:"
ls -la "${DIST_DIR}" | head -30